addons:
  sonarcloud:
    organization: "incountry"

git:
  depth: false

language: python
python: 3.7
node_js: 12.16

jobs:
  include:
    - stage: build
      name: "Scan code with Snyk, run tests, run Sonar Quality Gate"
      before_install:
        # Switch to newer NodeJS to prevent SNYK scan issues
        - nvm install v12.16.0
        - nvm use v12.16.0
        # Install Sonar-scanner
        - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONARSCANNER_VERSION}-linux.zip
        - unzip -q sonar-scanner-cli-${SONARSCANNER_VERSION}-linux.zip -d /home/travis/bin
      script:
        # Print debug information
        - echo "Building for branch=$TRAVIS_BRANCH, PR=${TRAVIS_PULL_REQUEST} ..."; env | grep "COMMIT\|PULL\|BRANCH"
        # Perform the build
        - ./travis-build.sh
    - stage: build
      name: "Run integration tests"
      before_install:
        - pipenv sync --dev
      script:
        - pipenv run integrations

stages:
  - name: build

env:
  global:
    # App properties
    - APP_NAME=sdk-python
    - PIPENV_VERBOSITY=-1 # Do not print pipenv 'running in virtual environment' warnings
    # Versions of deps
    - SONARSCANNER_VERSION=4.3.0.2102
