addons:
  sonarcloud:
    organization: "incountry"

language: python
python:
  - "3.7"

before_install:
  #  for sonar test coverage metric
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git fetch --no-tags https://github.com/incountry/sdk-python.git +refs/heads/$TRAVIS_BRANCH:refs/remotes/origin/$TRAVIS_BRANCH; fi

install:
  - pip3 install bandit
  - if [[ ($TRAVIS_BRANCH == "master") && ($TRAVIS_EVENT_TYPE == "cron") ]]; then npm install -g snyk; fi
  - pipenv sync

script:
  - if [[ ($TRAVIS_BRANCH == "master") && ($TRAVIS_EVENT_TYPE == "cron") ]]; then snyk monitor --org=incountry; fi
  - pipenv sync --dev
  - pipenv run check-format
  - pipenv run check-flake8
  - pipenv run tests
  - pipenv run integrations
  - bandit --ini bandit.ini -r -o bandit.json -f json
  - sonar-scanner
