addons:
  sonarcloud:
    organization: "incountry"

git:
  depth: false

language: python
python: 3.7
node_js: 11

jobs:
  include:
    - stage: build
      name: "Scan code with Snyk, run tests, run Sonar Quality Gate"
      script:
        # Print debug information
        - echo "Building for branch=$TRAVIS_BRANCH, PR=${TRAVIS_PULL_REQUEST} ..."; env | grep "COMMIT\|PULL\|BRANCH"
        # Perform the build
        - ./travis-build.sh
    - stage: build
      name: "Run integration tests"
      before_install:
        - pipenv sync --dev
      script:
        - pipenv run integrations

stages:
  - name: build

env:
  global:
    # App properties
    - APP_NAME=sdk-python
    - PIPENV_VERBOSITY=-1 # Do not print pipenv 'running in virtual environment' warnings
