addons:
  sonarcloud:
    organization: "incountry"

language: python
python:
  - "3.7"
node_js:
  - 11

before_install:
  #  for sonar test coverage metric
  - git fetch --no-tags https://github.com/incountry/sdk-python.git +refs/heads/develop:refs/remotes/origin/develop
  - git fetch --no-tags https://github.com/incountry/sdk-python.git +refs/heads/master:refs/remotes/origin/master

install:
  - pip3 install bandit
  - if [[ ($TRAVIS_BRANCH == "master") && ($TRAVIS_EVENT_TYPE == "cron") ]]; then npm install -g snyk; fi
  - pipenv sync

script:
  - if [[ ($TRAVIS_BRANCH == "master") && ($TRAVIS_EVENT_TYPE == "cron") ]]; then snyk monitor --org=incountry; fi
  - pipenv sync --dev
  - pipenv run check-format
  - pipenv run check-flake8
  - pipenv run tests
  - pipenv run integrations
  - bandit --ini bandit.ini -r -o bandit.json -f json
  - sonar-scanner
